export * as BasicMessage from "$lib/protocols/basic-message/index.js"
export * as OutOfBand from "$lib/protocols/out-of-band/index.js"
export * as PresentProof from "$lib/protocols/present-proof/index.js"
export * as TrustPing from "$lib/protocols/trust-ping/index.js"
export * as IssueCredential from "$lib/protocols/issue-credential/index.js"
export * as Routing from "$lib/protocols/routing/index.js"